import datetime
import random

from flask import Flask, render_template, request, send_file
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
import io

app = Flask(__name__)

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/invoice', methods=['POST'])
def invoice():
    seller_name = request.form['seller_name']
    seller_tax = request.form['seller_tax']
    client_name = request.form['client_name']
    services = request.form.getlist('service[]')
    prices = request.form.getlist('price[]')
    prices = [float(p) for p in prices]
    subtotal = sum(prices)
    vat = subtotal * 0.20
    total = subtotal + vat
    invoice_number = f"ED-{random.randint(1000, 9999)}"
    invoice_date = datetime.datetime.now().strftime("%d/%m/%Y")
    # Create PDF in memory
    buffer = io.BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Title
    pdf.setFont("Helvetica-Bold", 24)
    pdf.drawString(50, height - 60, "EXPRESSDEAL")
    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, height - 80, "Invoice")

    # Invoice number and date
    pdf.setFont("Helvetica", 11)
    pdf.drawString(50, height - 100, f"Invoice #: {invoice_number}")
    pdf.drawString(50, height - 118, f"Date: {invoice_date}")

    # Line
    pdf.line(50, height - 140, width - 50, height - 140)

    # Seller and client
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, height - 170, "From:")
    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, height - 190, seller_name)
    pdf.drawString(50, height - 208, f"Tax ID: {seller_tax}")

    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, height - 240, "To:")
    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, height - 260, client_name)

    # Line
    pdf.line(50, height - 280, width - 50, height - 280)

    # Services
    pdf.setFont("Helvetica-Bold", 12)
    pdf.drawString(50, height - 310, "Services:")
    y = height - 330
    for i, (service, price) in enumerate(zip(services, prices)):
        pdf.setFont("Helvetica", 12)
        pdf.drawString(50, y, f"- {service}")
        pdf.drawString(400, y, f"{price} MAD")
        y -= 20

    # Line
    pdf.line(50, y - 10, width - 50, y - 10)

    # Prices
    pdf.setFont("Helvetica", 12)
    pdf.drawString(50, y - 35, f"Subtotal:     {subtotal} MAD")
    pdf.drawString(50, y - 55, f"VAT (20%):    {vat} MAD")
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(50, y - 85, f"TOTAL:        {total} MAD")

    # Footer
    pdf.setFont("Helvetica", 10)
    pdf.drawString(50, 50, "Generated by ExpressDeal")

    pdf.save()
    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name=f"invoice_{client_name}.pdf",
        mimetype='application/pdf'
    )

if __name__ == '__main__':
    app.run(debug=True)
